# Generated by Django 4.2.6 on 2023-11-05 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr_management', '0018_alter_availabletime_from_time_alter_availabletime_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=25)),
                ('residual_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=25)),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Partly paid'), (3, 'Done'), (4, 'Cancelled'), (5, 'Expired')], default=1)),
                ('description', models.TextField()),
                ('craeted_at', models.DateTimeField(auto_now_add=True)),
                ('available_till', models.DateTimeField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_management.patient')),
            ],
        ),
    ]
