# Generated by Django 4.2.6 on 2023-11-05 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.IntegerField(choices=[(1, 'Cash'), (2, 'Plastic Card'), (3, 'Insurance')], default=1)),
                ('amount', models.DecimalField(decimal_places=2, default=1.0, max_digits=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.invoice')),
            ],
        ),
    ]
