# Generated by Django 4.2.6 on 2023-11-06 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_invoice_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='craeted_at',
            new_name='created_at',
        ),
    ]
