# Generated by Django 4.2.6 on 2023-11-25 14:15

from django.db import migrations, models
import django.db.models.deletion
import payments.validators


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_rename_craeted_at_invoice_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.invoice'),
        ),
    ]
