# Generated by Django 4.2.6 on 2024-02-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_payment_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='discount',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
