# Generated by Django 4.2.6 on 2024-02-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('payments', '0007_invoiceservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceservice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='invoiceservice',
            unique_together={('content_type', 'object_id', 'invoice')},
        ),
    ]
