# Generated by Django 4.2.6 on 2024-02-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_invoiceservice_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceservice',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
