# Generated by Django 4.2.6 on 2024-02-22 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_invoiceservice_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='invoice_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.invoiceservice'),
        ),
    ]
