# Generated by Django 4.2.6 on 2024-02-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_payment_invoice_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='invoice_service',
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice_service',
            field=models.ManyToManyField(null=True, to='payments.invoiceservice'),
        ),
    ]
