# Generated by Django 4.2.6 on 2024-02-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_remove_payment_invoice_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='invoice_service',
            field=models.ManyToManyField(to='payments.invoiceservice'),
        ),
    ]
