# Generated by Django 4.2.6 on 2024-03-04 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_alter_payment_invoice_service'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invoiceservice',
            unique_together=set(),
        ),
    ]
