# Generated by Django 4.2.6 on 2023-10-31 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_groups_customuser_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Female'), (1, 'Male')], default=1),
        ),
    ]
