# Generated by Django 4.2.6 on 2023-11-01 17:22

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curing',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='curing',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='Some Text'),
        ),
        migrations.AddField(
            model_name='curing',
            name='name',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='curing',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=25),
        ),
        migrations.CreateModel(
            name='CuringRegimen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug', models.CharField(max_length=255)),
                ('dosage', models.CharField(max_length=100)),
                ('times_in_a_day', models.PositiveBigIntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('curing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.curing')),
            ],
        ),
    ]
