# Generated by Django 4.2.6 on 2023-11-02 04:00

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0004_meal_mealamount_mealtime_admission'),
        ('hr_management', '0009_alter_availabletime_from_time_alter_availabletime_to'),
        ('events', '0002_curing_created_at_curing_description_curing_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnoz',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='diagnoz',
            name='name',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='diagnoz',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=25),
        ),
        migrations.AddField(
            model_name='diagnoz',
            name='responsible_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hr_management.staff'),
        ),
        migrations.AddField(
            model_name='diagnoz',
            name='room',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='departments.room'),
        ),
        migrations.CreateModel(
            name='DiagnoseProductUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=25)),
                ('measure', models.IntegerField(choices=[(1, 'MilliGramm'), (2, 'MilliLiter'), (3, 'Number of')], default=1)),
                ('diagnoz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.diagnoz')),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosePatientUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Waiting payment'), (2, 'In que'), (3, 'Done')], default=1)),
                ('result', ckeditor_uploader.fields.RichTextUploadingField(default='Nothing in here')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diagnoz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.diagnoz')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_management.patient')),
            ],
        ),
    ]
