# Generated by Django 4.2.6 on 2023-11-02 13:48

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0011_alter_availabletime_from_time_alter_availabletime_to'),
        ('departments', '0004_meal_mealamount_mealtime_admission'),
        ('events', '0004_rename_diagnosepatientusage_diagnozpatientusage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=25)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(default='type description in here')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consultant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hr_management.doctor')),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='departments.room')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsultingPatientUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Cancelled'), (1, 'Waiting payment'), (2, 'In que'), (3, 'Waiting diagnoses'), (4, 'Done')], default=1)),
                ('result', ckeditor_uploader.fields.RichTextUploadingField()),
                ('advice', ckeditor_uploader.fields.RichTextUploadingField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consulting', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='events.consulting')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hr_management.patient')),
                ('required_diagnoses', models.ManyToManyField(to='events.diagnoz')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug', models.CharField(max_length=255)),
                ('dosage', models.CharField(max_length=255)),
                ('times_in_a_day', models.PositiveBigIntegerField(default=1)),
                ('consulting_patient_usage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.consultingpatientusage')),
            ],
        ),
        migrations.AddField(
            model_name='diagnozpatientusage',
            name='consulting_patient_usage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.consultingpatientusage'),
        ),
    ]
