# Generated by Django 4.2.6 on 2023-11-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_consulting_consultingpatientusage_prescription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulting',
            name='status',
            field=models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1),
        ),
    ]
