# Generated by Django 4.2.6 on 2023-11-02 14:24

from django.db import migrations, models
import django.db.models.deletion
import events.validators


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0012_alter_availabletime_from_time_alter_availabletime_to'),
        ('events', '0006_consulting_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulting',
            name='consultant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hr_management.doctor', validators=[events.validators.validate_consultant]),
        ),
    ]
