# Generated by Django 4.2.6 on 2023-11-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_consulting_consultant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultingpatientusage',
            name='required_diagnoses',
            field=models.ManyToManyField(blank=True, to='events.diagnoz'),
        ),
    ]
