# Generated by Django 4.2.6 on 2023-11-02 14:44

from django.db import migrations, models
import django.db.models.deletion
import events.validators


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_consultingpatientusage_required_diagnoses'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnoz',
            name='status',
            field=models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1),
        ),
        migrations.AlterField(
            model_name='consultingpatientusage',
            name='consulting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='events.consulting', validators=[events.validators.validate_consulting]),
        ),
    ]
