# Generated by Django 4.2.6 on 2023-11-02 14:56

from django.db import migrations, models
import django.db.models.deletion
import events.validators


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_diagnoz_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnozproductusage',
            name='diagnoz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.diagnoz', validators=[events.validators.validate_diagnoz]),
        ),
    ]
