# Generated by Django 4.2.6 on 2023-11-02 15:18

from django.db import migrations, models
import django.db.models.deletion
import events.validators
import hr_management.validators


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0013_alter_availabletime_from_time_alter_availabletime_to'),
        ('events', '0010_alter_diagnozproductusage_diagnoz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultingpatientusage',
            name='required_diagnoses',
            field=models.ManyToManyField(blank=True, to='events.diagnoz', validators=[events.validators.validate_diagnoz]),
        ),
        migrations.AlterField(
            model_name='diagnoz',
            name='responsible_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hr_management.staff', validators=[hr_management.validators.validate_staff_is_vorking]),
        ),
        migrations.AlterField(
            model_name='diagnozpatientusage',
            name='consulting_patient_usage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.consultingpatientusage', validators=[events.validators.validate_consulting_patient_usage_dpu]),
        ),
        migrations.AlterField(
            model_name='diagnozpatientusage',
            name='diagnoz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.diagnoz', validators=[events.validators.validate_diagnoz]),
        ),
    ]
