# Generated by Django 4.2.6 on 2023-11-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_alter_consultingpatientusage_required_diagnoses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultingpatientusage',
            name='required_diagnoses',
            field=models.ManyToManyField(blank=True, to='events.diagnoz'),
        ),
    ]
