# Generated by Django 4.2.6 on 2023-11-26 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0011_alter_productscollection_barcode_data'),
        ('events', '0012_alter_consultingpatientusage_required_diagnoses'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnozproductusage',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.product'),
        ),
    ]
