doctors_data = [
    {
        'username': 'doctor41',
        'first_name': 'Oliver',
        'last_name': 'Rivera',
        'phone': '7021889999',
        'gender': 1,
        'address': '3838 Pine Lane',
    },
    {
        'username': 'doctor42',
        'first_name': 'Ava',
        'last_name': 'Wright',
        'phone': '555021777',
        'gender': 0,
        'address': '3939 Maple Street',
    },
    {
        'username': 'doctor43',
        'first_name': 'William',
        'last_name': 'White',
        'phone': '3334463755',
        'gender': 1,
        'address': '4040 Oak Avenue',
    },
    {
        'username': 'doctor44',
        'first_name': 'Ella',
        'last_name': 'Lewis',
        'phone': '1112456333',
        'gender': 0,
        'address': '4141 Elm Drive',
    },
    {
        'username': 'doctor45',
        'first_name': 'James',
        'last_name': 'Hall',
        'phone': '777884587',
        'gender': 1,
        'address': '4242 Cedar Road',
    },
    {
        'username': 'doctor46',
        'first_name': 'Sophia',
        'last_name': 'Young',
        'phone': '3334025555',
        'gender': 0,
        'address': '4343 Pine Lane',
    },
    {
        'username': 'doctor47',
        'first_name': 'Logan',
        'last_name': 'King',
        'phone': '5556007777',
        'gender': 1,
        'address': '4444 Maple Street',
    },
    {
        'username': 'doctor48',
        'first_name': 'Chloe',
        'last_name': 'Scott',
        'phone': '4443332222',
        'gender': 0,
        'address': '4545 Oak Avenue',
    },
    {
        'username': 'doctor49',
        'first_name': 'Daniel',
        'last_name': 'Lopez',
        'phone': '5554443333',
        'gender': 1,
        'address': '4646 Elm Drive',
    },
    {
        'username': 'doctor50',
        'first_name': 'Grace',
        'last_name': 'Adams',
        'phone': '2223334444',
        'gender': 0,
        'address': '4747 Cedar Road',
    },
    {
        'username': 'doctor51',
        'first_name': 'Joseph',
        'last_name': 'Morris',
        'phone': '77789689',
        'gender': 1,
        'address': '4848 Pine Lane',
    },
    {
        'username': 'doctor52',
        'first_name': 'Zoe',
        'last_name': 'Hall',
        'phone': '550967777',
        'gender': 0,
        'address': '4949 Maple Street',
    },
    {
        'username': 'doctor53',
        'first_name': 'Michael',
        'last_name': 'Young',
        'phone': '339645555',
        'gender': 1,
        'address': '5050 Oak Avenue',
    },
    {
        'username': 'doctor54',
        'first_name': 'Penelope',
        'last_name': 'Baker',
        'phone': '111220321',
        'gender': 0,
        'address': '5151 Elm Drive',
    },
    {
        'username': 'doctor55',
        'first_name': 'David',
        'last_name': 'King',
        'phone': '77783219',
        'gender': 1,
        'address': '5252 Cedar Road',
    },
    {
        'username': 'doctor56',
        'first_name': 'Lily',
        'last_name': 'Wright',
        'phone': '337845555',
        'gender': 0,
        'address': '5353 Pine Lane',
    },
    {
        'username': 'doctor57',
        'first_name': 'John',
        'last_name': 'Lewis',
        'phone': '5598667777',
        'gender': 1,
        'address': '5454 Maple Street',
    },
    {
        'username': 'doctor58',
        'first_name': 'Nora',
        'last_name': 'Scott',
        'phone': '4443332222',
        'gender': 0,
        'address': '5784 Maple Street',
    },
]