staff_specializations = [
    {'name': "Driver"},
    {'name': 'Doctor'},
    {'name': 'Security Guard'},
    {'name': 'Nurse'},
    {'name': 'Administrator'},
    {'name': 'Receptionist'},
    {'name': 'Pharmacist'},
    {'name': 'Laboratory Technician'},
    {'name': 'Radiologist'},
    {'name': 'Medical Transcriptionist'},
    {'name': 'Billing and Coding Specialist'},
    {'name': 'Medical Records Clerk'},
    {'name': 'Medical Librarian'},
    {'name': 'IT Support Specialist'},
    {'name': 'Maintenance Staff'},
    {'name': 'Housekeeping Staff'},
    {'name': 'Dietary Aide'},
    {'name': 'Patient Transporter'},
    {'name': 'Social Worker'},
]

doctor_specializations = [
    {'name': "Dentologist"},
    {'name': "Gastroenterologist"},
    {'name': "Cardiologist"},
    {'name': "Neurologist"},
    {'name': "Oncologist"},
    {'name': "Radiologist"},
    {'name': "Pediatrician"},
    {'name': "Urologist"},
    {'name': "Nephrologist"},
    {'name': "Anesthesiologist"},
]