staffs_data = [
    {
        'username': 'staff1',
        'first_name': 'Emily',
        'last_name': 'Garcia',
        'phone': '4324124444',
        'gender': 0,
        'address': '1011 Pine Lane',
    },
    {
        'username': 'staff2',
        'first_name': 'David',
        'last_name': 'Lee',
        'phone': '32133312333',
        'gender': 1,
        'address': '2222 Maple Street',
    },
    {
        'username': 'staff3',
        'first_name': 'John',
        'last_name': 'Smith',
        'phone': '1234567890',
        'gender': 1,
        'address': '123 Main Street',
    },
    {
        'username': 'staff4',
        'first_name': 'Sarah',
        'last_name': 'Johnson',
        'phone': '9876543210',
        'gender': 0,
        'address': '456 Elm Avenue',
    },
    {
        'username': 'staff5',
        'first_name': 'Michael',
        'last_name': 'Wilson',
        'phone': '5554443333',
        'gender': 1,
        'address': '789 Oak Drive',
    },
    {
        'username': 'staff6',
        'first_name': 'Jessica',
        'last_name': 'Martinez',
        'phone': '7778889999',
        'gender': 0,
        'address': '222 Pine Lane',
    },
    {
        'username': 'staff7',
        'first_name': 'Christopher',
        'last_name': 'Brown',
        'phone': '6665554444',
        'gender': 1,
        'address': '333 Maple Street',
    },
    {
        'username': 'staff8',
        'first_name': 'Emily',
        'last_name': 'Johnson',
        'phone': '1112223333',
        'gender': 0,
        'address': '444 Oak Avenue',
    },
    {
        'username': 'staff9',
        'first_name': 'Daniel',
        'last_name': 'Davis',
        'phone': '9998887777',
        'gender': 1,
        'address': '555 Elm Drive',
    },
    {
        'username': 'staff10',
        'first_name': 'Olivia',
        'last_name': 'Anderson',
        'phone': '3334445555',
        'gender': 0,
        'address': '666 Cedar Road',
    },
    {
        'username': 'staff11',
        'first_name': 'James',
        'last_name': 'Taylor',
        'phone': '2223334444',
        'gender': 1,
        'address': '777 Pine Lane',
    },
    {
        'username': 'staff12',
        'first_name': 'Sophia',
        'last_name': 'Thomas',
        'phone': '5556667777',
        'gender': 0,
        'address': '888 Maple Street',
    },
    {
        'username': 'staff13',
        'first_name': 'William',
        'last_name': 'Lee',
        'phone': '7776665555',
        'gender': 1,
        'address': '999 Oak Avenue',
    },
    {
        'username': 'staff14',
        'first_name': 'Ava',
        'last_name': 'Hernandez',
        'phone': '4445556666',
        'gender': 0,
        'address': '1010 Elm Drive',
    },
    {
        'username': 'staff15',
        'first_name': 'Ethan',
        'last_name': 'Gonzalez',
        'phone': '1112223333',
        'gender': 1,
        'address': '1212 Cedar Road',
    },
    {
        'username': 'staff16',
        'first_name': 'Mia',
        'last_name': 'Rodriguez',
        'phone': '7778889999',
        'gender': 0,
        'address': '1313 Pine Lane',
    },
    {
        'username': 'staff17',
        'first_name': 'Alexander',
        'last_name': 'Lopez',
        'phone': '3334445555',
        'gender': 1,
        'address': '1414 Maple Street',
    },
    {
        'username': 'staff18',
        'first_name': 'Emma',
        'last_name': 'Perez',
        'phone': '5554443333',
        'gender': 0,
        'address': '1515 Oak Avenue',
    },
    {
        'username': 'staff19',
        'first_name': 'Jackson',
        'last_name': 'Wang',
        'phone': '8889990000',
        'gender': 1,
        'address': '1616 Elm Drive',
    },
    {
        'username': 'staff20',
        'first_name': 'Isabella',
        'last_name': 'Gomez',
        'phone': '4443332222',
        'gender': 0,
        'address': '1717 Cedar Road',
    },
]