# Generated by Django 4.2.6 on 2023-10-31 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hr_management.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0003_customuser_address_customuser_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('date_of_birth', models.DateField()),
                ('insurance_provider', models.CharField(blank=True, max_length=255, validators=[hr_management.validators.validate_insurance_fields])),
                ('insurance_policy_number', models.CharField(blank=True, max_length=100, validators=[hr_management.validators.validate_insurance_fields])),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('account.customuser',),
        ),
    ]
