# Generated by Django 4.2.6 on 2023-10-31 10:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('account', '0004_alter_customuser_options'),
        ('hr_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorSpecialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='specializations/doctors/image/')),
                ('craeted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StuffSpecialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='specializations/stuffs/image/')),
                ('craeted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='patient',
            name='insurance_policy_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='insurance_provider',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='Stuff',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('image', models.ImageField(blank=True, upload_to='stuffs/images/')),
                ('working', models.BooleanField(default=True)),
                ('salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=25)),
                ('salary_currency', models.IntegerField(choices=[(0, 'UZS'), (1, 'USD'), (2, 'EUR')], default=0)),
                ('barcode_data', models.CharField(max_length=100, unique=True)),
                ('barcode_file_path', models.CharField(max_length=255, unique=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='departments.department')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hr_management.stuffspecialization')),
            ],
            options={
                'abstract': False,
            },
            bases=('account.customuser',),
        ),
        migrations.CreateModel(
            name='AvailableTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thoursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], default=1)),
                ('from_time', models.TimeField(default=datetime.time(15, 50, 18, 843784))),
                ('to', models.TimeField(default=datetime.time(15, 50, 18, 843784))),
                ('stuff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_management.stuff')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('stuff_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hr_management.stuff')),
                ('postion', models.IntegerField(choices=[(0, 'Junior'), (1, 'Senior'), (2, 'Consultant'), (3, 'Surgeon')], default=0)),
                ('perofession', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hr_management.doctorspecialization')),
            ],
            options={
                'abstract': False,
            },
            bases=('hr_management.stuff',),
        ),
    ]
