# Generated by Django 4.2.6 on 2023-10-31 10:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0002_doctorspecialization_stuffspecialization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabletime',
            name='from_time',
            field=models.TimeField(default=datetime.time(15, 56, 5, 77128)),
        ),
        migrations.AlterField(
            model_name='availabletime',
            name='to',
            field=models.TimeField(default=datetime.time(15, 56, 5, 77128)),
        ),
        migrations.AlterField(
            model_name='stuff',
            name='barcode_data',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='stuff',
            name='barcode_file_path',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
