# Generated by Django 4.2.6 on 2023-10-31 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0003_alter_availabletime_from_time_alter_availabletime_to_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='postion',
            new_name='position',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='perofession',
            new_name='profession',
        ),
        migrations.AlterField(
            model_name='availabletime',
            name='from_time',
            field=models.TimeField(default=datetime.time(16, 9, 10, 420625)),
        ),
        migrations.AlterField(
            model_name='availabletime',
            name='to',
            field=models.TimeField(default=datetime.time(16, 9, 10, 420625)),
        ),
    ]
