# Generated by Django 4.2.6 on 2023-10-31 11:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0005_alter_availabletime_from_time_alter_availabletime_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorspecialization',
            old_name='craeted_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='stuffspecialization',
            old_name='craeted_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='availabletime',
            name='from_time',
            field=models.TimeField(default=datetime.time(16, 42, 10, 993050)),
        ),
        migrations.AlterField(
            model_name='availabletime',
            name='to',
            field=models.TimeField(default=datetime.time(16, 42, 10, 993050)),
        ),
    ]
