# Generated by Django 4.2.6 on 2023-10-31 12:23

import datetime
from django.db import migrations, models
import hr_management.validators


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0007_alter_availabletime_from_time_alter_availabletime_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='_file',
            field=models.FileField(upload_to='achievements/docs/', validators=[hr_management.validators.validate_file_type, hr_management.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='availabletime',
            name='from_time',
            field=models.TimeField(default=datetime.time(17, 23, 30, 665056)),
        ),
        migrations.AlterField(
            model_name='availabletime',
            name='to',
            field=models.TimeField(default=datetime.time(17, 23, 30, 665056)),
        ),
    ]
