# Generated by Django 4.2.6 on 2023-11-24 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0020_alter_availabletime_from_time_alter_availabletime_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabletime',
            name='from_time',
            field=models.TimeField(default=datetime.time(21, 4, 3, 203643)),
        ),
        migrations.AlterField(
            model_name='availabletime',
            name='to',
            field=models.TimeField(default=datetime.time(21, 4, 3, 203643)),
        ),
        migrations.AlterField(
            model_name='staff',
            name='barcode_data',
            field=models.CharField(blank=True, max_length=13, unique=True),
        ),
    ]
