# Generated by Django 4.2.6 on 2024-02-01 19:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0027_alter_availabletime_from_time_alter_availabletime_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabletime',
            name='from_time',
            field=models.TimeField(default=datetime.time(0, 43, 10, 388416)),
        ),
        migrations.AlterField(
            model_name='availabletime',
            name='to',
            field=models.TimeField(default=datetime.time(0, 43, 10, 388416)),
        ),
    ]
