# Generated by Django 4.2.6 on 2023-11-10 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=25)),
                ('amount_in_stock', models.DecimalField(decimal_places=2, default=0.0, max_digits=25)),
                ('measure', models.IntegerField(choices=[(0, 'MilliGramm'), (1, 'Gramm'), (2, 'KiloGramm'), (3, 'Ton'), (4, 'MilliLiter'), (5, 'Liter'), (6, 'Peace')], default=2)),
                ('description', models.TextField(blank=True)),
                ('location', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.itemcategory')),
            ],
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.section'),
        ),
    ]
