# Generated by Django 4.2.6 on 2023-11-10 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='warehouse.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=25)),
                ('measure', models.IntegerField(choices=[(0, 'MilliGramm'), (1, 'Gramm'), (2, 'KiloGramm'), (3, 'Ton'), (4, 'MilliLiter'), (5, 'Liter'), (6, 'Peace')], default=2)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.product')),
            ],
        ),
    ]
