# Generated by Django 4.2.6 on 2023-11-10 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0019_alter_availabletime_from_time_alter_availabletime_to'),
        ('warehouse', '0003_order_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=25)),
                ('measure', models.IntegerField(choices=[(0, 'MilliGramm'), (1, 'Gramm'), (2, 'KiloGramm'), (3, 'Ton'), (4, 'MilliLiter'), (5, 'Liter'), (6, 'Peace')], default=1)),
                ('usable_till', models.DateField()),
                ('barcode_data', models.CharField(max_length=11)),
                ('barcode_file', models.ImageField(upload_to='products_collection/barcodes/')),
                ('is_exists', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='warehouse.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Shipping'), (3, 'Delivered'), (4, 'Cancelled')], default=1),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='usable_till',
            field=models.DateField(null=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProductUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('taken_at', models.DateTimeField(auto_now_add=True)),
                ('product_collections', models.ManyToManyField(to='warehouse.productscollection')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr_management.staff')),
            ],
        ),
    ]
