# Generated by Django 4.2.6 on 2023-11-10 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_productscollection_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='usable_till',
            field=models.DateField(null=True),
        ),
    ]
