# Generated by Django 4.2.6 on 2023-11-17 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_alter_orderitem_usable_till'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productusage',
            name='product_collections',
            field=models.ManyToManyField(related_name='collections', to='warehouse.productscollection'),
        ),
    ]
