# Generated by Django 4.2.6 on 2023-11-17 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_alter_productusage_product_collections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productusage',
            name='product_collections',
        ),
        migrations.AddField(
            model_name='productusage',
            name='collections',
            field=models.ManyToManyField(to='warehouse.productscollection'),
        ),
    ]
