# Generated by Django 4.2.6 on 2023-11-24 05:09

from django.db import migrations, models
import warehouse.validators


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0007_remove_productusage_product_collections_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productusage',
            name='collections',
            field=models.ManyToManyField(to='warehouse.productscollection', validators=[warehouse.validators.validate_product_collection]),
        ),
    ]
