# Generated by Django 4.2.6 on 2023-11-24 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0008_alter_productusage_collections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productusage',
            name='collections',
            field=models.ManyToManyField(to='warehouse.productscollection'),
        ),
    ]
