# Generated by Django 4.2.6 on 2023-11-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0009_alter_productusage_collections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productscollection',
            name='barcode_data',
            field=models.CharField(editable=False, max_length=13),
        ),
        migrations.AlterField(
            model_name='productscollection',
            name='barcode_file',
            field=models.ImageField(editable=False, upload_to='products_collection/barcodes/'),
        ),
    ]
