# Generated by Django 4.2.6 on 2023-11-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0010_alter_productscollection_barcode_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productscollection',
            name='barcode_data',
            field=models.CharField(editable=False, max_length=13, unique=True),
        ),
    ]
