# Generated by Django 4.2.6 on 2023-11-27 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0006_departmentstorage'),
        ('warehouse', '0011_alter_productscollection_barcode_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='productusage',
            name='for_storage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='departments.departmentstorage'),
        ),
        migrations.CreateModel(
            name='ProductInStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=25)),
                ('measure', models.IntegerField(choices=[(0, 'MilliGramm'), (1, 'Gramm'), (2, 'KiloGramm'), (3, 'Ton'), (4, 'MilliLiter'), (5, 'Liter'), (6, 'Peace')], default=2)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.product')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.departmentstorage')),
            ],
        ),
    ]
