departments_data = [
    {'name': "Dentology", 'building': "Building A 1-floor"},
    {'name': "Gastrology", 'building': "Building A 2-3 floors"},
    {'name': "Cardiology", 'building': "Building B 2nd floor"},
    {'name': "Orthopedics", 'building': "Building C 3rd floor"},
    {'name': "Neurology", 'building': "Building D 4th floor"},
    {'name': "Ophthalmology", 'building': "Building E 5th floor"},
    {'name': "Pediatrics", 'building': "Building F 6th floor"},
    {'name': "Dermatology", 'building': "Building G 7th floor"},
    {'name': "Oncology", 'building': "Building H 8th floor"},
    {'name': "Urology", 'building': "Building I 9th floor"},
    {'name': "Endocrinology", 'building': "Building J 10th floor"},
    {'name': "Psychiatry", 'building': "Building K 11th floor"},
    {'name': "Radiology", 'building': "Building L 12th floor"},
    {'name': "Nephrology", 'building': "Building M 13th floor"},
    {'name': "Gynecology", 'building': "Building N 14th floor"},
]