room_names = [
    "Room 1",
    "Room 2",
    "Room 3",
    "Room 4",
    "Room 5",
    "Room 6",
    "Room 7",
    "Room 8",
    "Room 9",
    "Room 10",
    "Room 11",
    "Room 12",
    "Room 13",
    "Room 14",
    "Room 15",
    "Room 16",
    "Room 17",
    "Room 18",
    "Room 19",
    "Room 20",
]

stuff_names = [
    "Bed",
    "Chair",
    "Table",
    "Cabinet",
    "Computer",
    "Whiteboard",
    "Stethoscope",
    "Oxygen Cylinder",
    "Surgical Instruments",
    "Scalpel",
    "Gloves",
    "Thermometer",
    "Blood Pressure Monitor",
    "Syringe",
    "Medication",
    "IV Stand",
    "X-ray Machine",
    "Ultrasound Machine",
    "ECG Machine",
    "Nebulizer",
]