# Generated by Django 4.2.6 on 2023-11-01 16:49

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('hr_management', '0008_alter_availabletime_from_time_alter_availabletime_to'),
        ('departments', '0003_roomstuff_created_at_roomstuff_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MealAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('measure', models.IntegerField(choices=[(1, 'Gramm'), (2, 'Milliliter')], default=1)),
                ('meal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='departments.meal')),
            ],
        ),
        migrations.CreateModel(
            name='MealTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Breakfast', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=25)),
                ('time', models.TimeField()),
                ('amount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.mealamount')),
                ('department', models.ManyToManyField(to='departments.department')),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finishes_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'In process'), (3, 'Done'), (4, 'Cancelled')], default=1)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='departments.bed')),
                ('curings', models.ManyToManyField(to='events.curing')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.department')),
                ('diagnoses', models.ManyToManyField(blank=True, to='events.diagnoz')),
                ('meals', models.ManyToManyField(blank=True, to='departments.mealtime')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hr_management.patient')),
            ],
            options={
                'ordering': ['starts_at', 'status'],
            },
        ),
    ]
