# Generated by Django 4.2.6 on 2023-11-06 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0004_meal_mealamount_mealtime_admission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bed',
            name='department',
        ),
        migrations.AddField(
            model_name='room',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='departments.department'),
        ),
    ]
