# Generated by Django 4.2.6 on 2023-11-27 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0005_remove_bed_department_room_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.department')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.room')),
            ],
        ),
    ]
