# Generated by Django 4.2.6 on 2024-02-01 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0006_departmentstorage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='status',
            field=models.IntegerField(choices=[(0, 'Available'), (1, 'Occupied')], default=0),
        ),
    ]
